-- Generated by tests/schema.test.ts from the migrations. Do not edit.

CREATE TABLE "schema_migrations" (
  migration_id integer PRIMARY KEY NOT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE devices (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'dev_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  name TEXT NOT NULL,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE actors (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'act_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  kind TEXT NOT NULL CHECK (kind IN ('person', 'agent', 'system')),
  display_name TEXT NOT NULL,
  agent_id TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  CHECK ((kind = 'agent') = (agent_id IS NOT NULL))
) STRICT;

CREATE TABLE projects (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'proj_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*'),
  created_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  archived_at TEXT CHECK (archived_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE policies (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'pol_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  revision INTEGER NOT NULL CHECK (revision >= 1),
  rules TEXT NOT NULL CHECK (json_valid(rules)),
  created_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (project_id, revision)
) STRICT;

CREATE TABLE project_settings (
  project_id TEXT PRIMARY KEY NOT NULL REFERENCES projects (id),
  worktree_root TEXT,
  setup_command TEXT,
  check_command TEXT,
  copy_files TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(copy_files)),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE repository_bindings (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'repo_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  slug TEXT NOT NULL CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*'),
  role TEXT NOT NULL,
  display_name TEXT NOT NULL,
  remote_fingerprints TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(remote_fingerprints)),
  provider_repository_id TEXT,
  allowed_subpaths TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(allowed_subpaths)),
  default_base_ref TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  detached_at TEXT CHECK (detached_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (project_id, slug)
) STRICT;

CREATE TABLE repository_locations (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'loc_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  binding_id TEXT NOT NULL REFERENCES repository_bindings (id),
  device_id TEXT NOT NULL REFERENCES devices (id),
  kind TEXT NOT NULL CHECK (kind IN ('existing', 'managed')),
  path TEXT NOT NULL,
  observed_remotes TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(observed_remotes)),
  state TEXT NOT NULL CHECK (state IN ('ready', 'needs_access', 'changed', 'unavailable')),
  verified_at TEXT CHECK (verified_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (binding_id, device_id)
) STRICT;

CREATE TABLE artifacts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'art_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  sha256 TEXT NOT NULL CHECK (length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'),
  size INTEGER NOT NULL CHECK (size >= 0),
  media_type TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('brief', 'message', 'transcript', 'patch', 'log', 'report', 'findings', 'summary', 'other')),
  sensitivity TEXT NOT NULL DEFAULT 'normal' CHECK (sensitivity IN ('normal', 'may_contain_secrets')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE artifact_links (
  artifact_id TEXT NOT NULL REFERENCES artifacts (id),
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  role TEXT NOT NULL,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (artifact_id, subject_type, subject_id, role)
) STRICT;

CREATE INDEX repository_bindings_by_project ON repository_bindings (project_id);

CREATE INDEX artifacts_by_digest ON artifacts (sha256);

CREATE INDEX artifact_links_by_subject ON artifact_links (subject_type, subject_id);

CREATE TABLE tasks (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'task_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  slug TEXT NOT NULL CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*'),
  state TEXT NOT NULL CHECK (state IN ('draft', 'open', 'done', 'abandoned')),
  created_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  settled_at TEXT CHECK (settled_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (project_id, slug)
) STRICT;

CREATE TABLE task_repository_requirements (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'req_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  task_id TEXT NOT NULL REFERENCES tasks (id),
  binding_id TEXT NOT NULL REFERENCES repository_bindings (id),
  access TEXT NOT NULL CHECK (access IN ('read', 'write', 'observe')),
  allowed_roots TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(allowed_roots)),
  base_ref TEXT,
  required INTEGER NOT NULL DEFAULT 1 CHECK (required IN (0, 1)),
  UNIQUE (task_id, binding_id)
) STRICT;

CREATE TABLE workflow_definitions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wdef_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  name TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  retired_at TEXT CHECK (retired_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE workflow_versions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wver_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  definition_id TEXT NOT NULL REFERENCES workflow_definitions (id),
  version INTEGER NOT NULL CHECK (version >= 1),
  content_hash TEXT NOT NULL CHECK (length(content_hash) = 64 AND content_hash NOT GLOB '*[^0-9a-f]*'),
  definition TEXT NOT NULL CHECK (json_valid(definition)),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (definition_id, version)
) STRICT;

CREATE TABLE task_plans (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'plan_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  task_id TEXT NOT NULL REFERENCES tasks (id),
  workflow_version_id TEXT NOT NULL REFERENCES workflow_versions (id),
  parameters TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(parameters)),
  proposed_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  state TEXT NOT NULL CHECK (state IN ('proposed', 'accepted', 'replaced', 'declined')),
  proposed_at TEXT NOT NULL CHECK (proposed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  starts_at TEXT CHECK (starts_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  decided_at TEXT CHECK (decided_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE runs (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'run_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  task_id TEXT NOT NULL REFERENCES tasks (id),
  plan_id TEXT REFERENCES task_plans (id),
  workflow_version_id TEXT NOT NULL REFERENCES workflow_versions (id),
  policy_id TEXT NOT NULL REFERENCES policies (id),
  parameters TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(parameters)),
  budget TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(budget)),
  state TEXT NOT NULL CHECK (state IN ('admitted', 'running', 'suspended', 'succeeded', 'failed', 'cancelled')),
  end_reason TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE run_attempts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'ratt_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  run_id TEXT NOT NULL REFERENCES runs (id),
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  controller_generation INTEGER NOT NULL DEFAULT 1 CHECK (controller_generation >= 1),
  state TEXT NOT NULL CHECK (state IN ('active', 'succeeded', 'failed', 'cancelled', 'interrupted')),
  started_at TEXT NOT NULL CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (run_id, attempt_number)
) STRICT;

CREATE TABLE workspace_sets (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wset_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  run_attempt_id TEXT NOT NULL REFERENCES run_attempts (id),
  root_path TEXT NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('preparing', 'ready', 'published', 'cleaned', 'failed')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  cleaned_at TEXT CHECK (cleaned_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE workspaces (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 3) = 'ws_' AND length(id) = 35 AND substr(id, 4) NOT GLOB '*[^0-9a-f]*'),
  workspace_set_id TEXT NOT NULL REFERENCES workspace_sets (id),
  binding_id TEXT NOT NULL REFERENCES repository_bindings (id),
  path TEXT NOT NULL,
  base_ref TEXT NOT NULL,
  base_commit TEXT,
  branch TEXT NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('preparing', 'ready', 'published', 'cleaned', 'failed')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  cleaned_at TEXT CHECK (cleaned_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (workspace_set_id, binding_id)
) STRICT;

CREATE TABLE workflow_executions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'wexe_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  run_id TEXT NOT NULL UNIQUE REFERENCES runs (id),
  workflow_version_id TEXT NOT NULL REFERENCES workflow_versions (id),
  graph_revision INTEGER NOT NULL DEFAULT 1 CHECK (graph_revision >= 1),
  state TEXT NOT NULL CHECK (state IN ('running', 'succeeded', 'failed', 'cancelled')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE graph_patches (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 6) = 'patch_' AND length(id) = 38 AND substr(id, 7) NOT GLOB '*[^0-9a-f]*'),
  execution_id TEXT NOT NULL REFERENCES workflow_executions (id),
  expected_revision INTEGER NOT NULL CHECK (expected_revision >= 1),
  operations TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(operations)),
  authority_delta TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(authority_delta)),
  budget_delta TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(budget_delta)),
  rationale_artifact_id TEXT REFERENCES artifacts (id),
  proposed_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  state TEXT NOT NULL CHECK (state IN ('proposed', 'held', 'accepted', 'rejected', 'undone')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  hold_until TEXT CHECK (hold_until GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  decided_at TEXT CHECK (decided_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE execution_graph_revisions (
  execution_id TEXT NOT NULL REFERENCES workflow_executions (id),
  revision INTEGER NOT NULL CHECK (revision >= 1),
  graph TEXT NOT NULL CHECK (json_valid(graph)),
  cause TEXT NOT NULL CHECK (cause IN ('materialized', 'patch')),
  patch_id TEXT REFERENCES graph_patches (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (execution_id, revision),
  CHECK ((cause = 'patch') = (patch_id IS NOT NULL))
) STRICT;

CREATE TABLE nodes (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'node_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  execution_id TEXT NOT NULL REFERENCES workflow_executions (id),
  node_key TEXT NOT NULL,
  iteration INTEGER NOT NULL DEFAULT 0 CHECK (iteration >= 0),
  type TEXT NOT NULL CHECK (type IN ('deterministic_action', 'agent', 'integration', 'human_decision', 'condition', 'bounded_map', 'join', 'verification', 'compensation', 'subworkflow', 'bounded_loop')),
  added_in_revision INTEGER NOT NULL CHECK (added_in_revision >= 1),
  config TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(config)),
  state TEXT NOT NULL CHECK (state IN ('pending', 'ready', 'running', 'succeeded', 'failed', 'skipped', 'cancelled', 'uncertain')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (execution_id, node_key, iteration)
) STRICT;

CREATE INDEX tasks_by_project ON tasks (project_id, state);

CREATE INDEX task_plans_by_task ON task_plans (task_id);

CREATE INDEX runs_by_task ON runs (task_id);

CREATE INDEX workspace_sets_by_run_attempt ON workspace_sets (run_attempt_id);

CREATE INDEX graph_patches_by_execution ON graph_patches (execution_id);

CREATE TABLE threads (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'thr_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  kind TEXT NOT NULL CHECK (kind IN ('coordinator', 'task', 'step')),
  owner_actor_id TEXT REFERENCES actors (id),
  task_id TEXT REFERENCES tasks (id),
  node_id TEXT REFERENCES nodes (id),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK (
    (kind = 'coordinator' AND owner_actor_id IS NOT NULL AND task_id IS NULL AND node_id IS NULL)
    OR (kind = 'task' AND owner_actor_id IS NULL AND task_id IS NOT NULL AND node_id IS NULL)
    OR (kind = 'step' AND owner_actor_id IS NULL AND task_id IS NOT NULL AND node_id IS NOT NULL)
  )
) STRICT;

CREATE TABLE user_inputs (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 6) = 'input_' AND length(id) = 38 AND substr(id, 7) NOT GLOB '*[^0-9a-f]*'),
  thread_id TEXT NOT NULL REFERENCES threads (id),
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  command_id TEXT NOT NULL UNIQUE CHECK (substr(command_id, 1, 4) = 'cmd_'),
  disposition TEXT NOT NULL CHECK (disposition IN ('after_current', 'interrupt_and_continue', 'supersede_pending', 'cancel_run')),
  body TEXT NOT NULL,
  author_actor_id TEXT NOT NULL REFERENCES actors (id),
  state TEXT NOT NULL CHECK (state IN ('queued', 'delivered', 'superseded')),
  accepted_at TEXT NOT NULL CHECK (accepted_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (thread_id, sequence)
) STRICT;

CREATE TABLE turn_deliveries (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'turn_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  thread_id TEXT NOT NULL REFERENCES threads (id),
  provider_session_id TEXT NOT NULL REFERENCES provider_sessions (id),
  node_attempt_id TEXT REFERENCES node_attempts (id),
  controller_generation INTEGER NOT NULL CHECK (controller_generation >= 1),
  brief_artifact_id TEXT REFERENCES artifacts (id),
  state TEXT NOT NULL CHECK (state IN ('pending', 'delivered', 'completed', 'interrupted', 'interruption_uncertain', 'failed')),
  requested_at TEXT NOT NULL CHECK (requested_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  delivered_at TEXT CHECK (delivered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE turn_delivery_inputs (
  delivery_id TEXT NOT NULL REFERENCES turn_deliveries (id),
  user_input_id TEXT NOT NULL REFERENCES user_inputs (id),
  position INTEGER NOT NULL CHECK (position >= 1),
  PRIMARY KEY (delivery_id, user_input_id)
) STRICT;

CREATE TABLE thread_items (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'item_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  thread_id TEXT NOT NULL REFERENCES threads (id),
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  kind TEXT NOT NULL CHECK (kind IN ('user_message', 'agent_message', 'agent_thought', 'tool_call', 'plan', 'step_result', 'notice')),
  user_input_id TEXT REFERENCES user_inputs (id),
  delivery_id TEXT REFERENCES turn_deliveries (id),
  provider_session_id TEXT REFERENCES provider_sessions (id),
  content TEXT NOT NULL CHECK (json_valid(content)),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (thread_id, sequence),
  CHECK ((kind = 'user_message') = (user_input_id IS NOT NULL))
) STRICT;

CREATE TABLE thread_summaries (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'sum_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  thread_id TEXT NOT NULL REFERENCES threads (id),
  covers_from_sequence INTEGER NOT NULL CHECK (covers_from_sequence >= 1),
  covers_to_sequence INTEGER NOT NULL,
  artifact_id TEXT NOT NULL REFERENCES artifacts (id),
  written_by TEXT NOT NULL,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  CHECK (covers_to_sequence >= covers_from_sequence)
) STRICT;

CREATE INDEX threads_by_project ON threads (project_id);

CREATE UNIQUE INDEX one_coordinator_thread_per_owner ON threads (project_id, owner_actor_id) WHERE kind = 'coordinator';

CREATE UNIQUE INDEX one_thread_per_task ON threads (task_id) WHERE kind = 'task';

CREATE UNIQUE INDEX one_thread_per_step ON threads (node_id) WHERE kind = 'step';

CREATE INDEX user_inputs_queued ON user_inputs (thread_id, sequence) WHERE state = 'queued';

CREATE INDEX turn_deliveries_by_thread ON turn_deliveries (thread_id);

CREATE INDEX turn_deliveries_by_session ON turn_deliveries (provider_session_id);

CREATE INDEX thread_summaries_by_thread ON thread_summaries (thread_id, covers_to_sequence);

CREATE TABLE agent_installations (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'inst_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  device_id TEXT NOT NULL REFERENCES devices (id),
  agent_id TEXT NOT NULL,
  agent_version TEXT,
  adapter_version TEXT,
  protocol_version INTEGER,
  status TEXT NOT NULL CHECK (status IN ('supported', 'degraded', 'blocked', 'missing')),
  capabilities TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(capabilities)),
  probed_at TEXT NOT NULL CHECK (probed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE principals (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'prin_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  agent_id TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES devices (id),
  subject_hint TEXT NOT NULL,
  auth_mode TEXT NOT NULL CHECK (auth_mode IN ('vendor_cli', 'api_key', 'oauth', 'enterprise', 'workload')),
  observed_at TEXT NOT NULL CHECK (observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE account_statuses (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'acct_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  principal_id TEXT NOT NULL REFERENCES principals (id),
  state TEXT NOT NULL CHECK (state IN ('ok', 'warning', 'limited')),
  windows TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(windows)),
  source TEXT NOT NULL CHECK (source IN ('error', 'side_channel')),
  observed_at TEXT NOT NULL CHECK (observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE provider_sessions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'sess_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  thread_id TEXT NOT NULL REFERENCES threads (id),
  agent_id TEXT NOT NULL,
  model TEXT,
  effort TEXT,
  principal_id TEXT REFERENCES principals (id),
  installation_id TEXT REFERENCES agent_installations (id),
  external_session_id TEXT,
  run_attempt_id TEXT REFERENCES run_attempts (id),
  controller_generation INTEGER CHECK (controller_generation >= 1),
  brief_artifact_id TEXT REFERENCES artifacts (id),
  state TEXT NOT NULL CHECK (state IN ('probing', 'auth_required', 'ready', 'starting', 'active', 'waiting_approval', 'completed', 'cancelling', 'cancelled', 'lost', 'reconciling', 'uncertain', 'failed', 'superseded')),
  superseded_by_session_id TEXT REFERENCES provider_sessions (id),
  last_event_sequence INTEGER NOT NULL DEFAULT 0 CHECK (last_event_sequence >= 0),
  started_at TEXT NOT NULL CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK ((state = 'superseded') = (superseded_by_session_id IS NOT NULL))
) STRICT;

CREATE TABLE provider_events (
  session_id TEXT NOT NULL REFERENCES provider_sessions (id),
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  direction TEXT NOT NULL CHECK (direction IN ('in', 'out')),
  method TEXT,
  payload TEXT NOT NULL CHECK (json_valid(payload)),
  received_at TEXT NOT NULL CHECK (received_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  PRIMARY KEY (session_id, sequence)
) STRICT;

CREATE TABLE processes (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'proc_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  device_id TEXT NOT NULL REFERENCES devices (id),
  provider_session_id TEXT REFERENCES provider_sessions (id),
  run_attempt_id TEXT REFERENCES run_attempts (id),
  purpose TEXT NOT NULL CHECK (purpose IN ('agent', 'verify', 'setup', 'git', 'other')),
  executable TEXT NOT NULL,
  executable_version TEXT,
  pid INTEGER NOT NULL CHECK (pid > 0),
  process_group_id INTEGER CHECK (process_group_id > 0),
  args_redacted TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(args_redacted)),
  environment_digest TEXT,
  controller_generation INTEGER CHECK (controller_generation >= 1),
  state TEXT NOT NULL CHECK (state IN ('running', 'exited', 'killed', 'unknown')),
  started_at TEXT NOT NULL CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  exit_code INTEGER,
  signal TEXT
) STRICT;

CREATE TABLE node_attempts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'natt_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  node_id TEXT NOT NULL REFERENCES nodes (id),
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  run_attempt_id TEXT NOT NULL REFERENCES run_attempts (id),
  controller_generation INTEGER NOT NULL CHECK (controller_generation >= 1),
  provider_session_id TEXT REFERENCES provider_sessions (id),
  state TEXT NOT NULL CHECK (state IN ('ready', 'admitted', 'running', 'waiting_attention', 'verifying', 'succeeded', 'failed', 'cancelling', 'cancelled', 'uncertain', 'reconciling', 'superseded')),
  input TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(input)),
  output TEXT CHECK (json_valid(output)),
  output_artifact_id TEXT REFERENCES artifacts (id),
  error_class TEXT,
  admitted_at TEXT NOT NULL CHECK (admitted_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  started_at TEXT CHECK (started_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  ended_at TEXT CHECK (ended_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  UNIQUE (node_id, attempt_number)
) STRICT;

CREATE INDEX account_statuses_by_principal ON account_statuses (principal_id, observed_at);

CREATE INDEX provider_sessions_by_thread ON provider_sessions (thread_id);

CREATE INDEX provider_sessions_by_run_attempt ON provider_sessions (run_attempt_id);

CREATE INDEX processes_by_session ON processes (provider_session_id);

CREATE INDEX processes_running ON processes (state) WHERE state = 'running';

CREATE INDEX node_attempts_by_session ON node_attempts (provider_session_id);

CREATE INDEX node_attempts_by_run_attempt ON node_attempts (run_attempt_id);

CREATE TABLE permission_requests (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'perm_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  provider_session_id TEXT NOT NULL REFERENCES provider_sessions (id),
  node_attempt_id TEXT REFERENCES node_attempts (id),
  tool_call_id TEXT NOT NULL,
  tool_kind TEXT NOT NULL CHECK (tool_kind IN ('read', 'edit', 'delete', 'move', 'search', 'execute', 'think', 'fetch', 'switch_mode', 'other')),
  title TEXT NOT NULL,
  raw_input TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(raw_input)),
  options TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(options)),
  action_digest TEXT NOT NULL,
  state TEXT NOT NULL CHECK (state IN ('open', 'decided', 'cancelled')),
  received_at TEXT NOT NULL CHECK (received_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE attention_requests (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'attn_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  project_id TEXT NOT NULL REFERENCES projects (id),
  task_id TEXT REFERENCES tasks (id),
  node_attempt_id TEXT REFERENCES node_attempts (id),
  permission_request_id TEXT REFERENCES permission_requests (id),
  kind TEXT NOT NULL CHECK (kind IN ('permission', 'question', 'stuck', 'plan', 'graph_patch', 'usage_limit', 'review_disagreement')),
  addressee_actor_id TEXT REFERENCES actors (id),
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  action_digest TEXT,
  policy_id TEXT REFERENCES policies (id),
  state TEXT NOT NULL CHECK (state IN ('open', 'answered', 'expired', 'withdrawn')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  expires_at TEXT CHECK (expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  answered_at TEXT CHECK (answered_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
  CHECK ((kind = 'permission') = (permission_request_id IS NOT NULL))
) STRICT;

CREATE TABLE decisions (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'dec_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  permission_request_id TEXT REFERENCES permission_requests (id),
  attention_request_id TEXT REFERENCES attention_requests (id),
  outcome TEXT NOT NULL CHECK (outcome IN ('allow_once', 'allow_always', 'reject_once', 'reject_always', 'answer', 'dismiss')),
  reason TEXT,
  decided_by_actor_id TEXT NOT NULL REFERENCES actors (id),
  decided_by_session_id TEXT REFERENCES provider_sessions (id),
  rule TEXT CHECK (json_valid(rule)),
  policy_id TEXT REFERENCES policies (id),
  action_digest TEXT,
  decided_at TEXT NOT NULL CHECK (decided_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  consumed_at TEXT CHECK (consumed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  CHECK (permission_request_id IS NOT NULL OR attention_request_id IS NOT NULL)
) STRICT;

CREATE INDEX permission_requests_open ON permission_requests (provider_session_id) WHERE state = 'open';

CREATE INDEX attention_requests_by_project ON attention_requests (project_id, state);

CREATE INDEX attention_requests_by_task ON attention_requests (task_id);

CREATE INDEX decisions_by_permission_request ON decisions (permission_request_id);

CREATE INDEX decisions_by_attention_request ON decisions (attention_request_id);

CREATE TABLE change_sets (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'chg_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  task_id TEXT NOT NULL REFERENCES tasks (id),
  run_id TEXT NOT NULL REFERENCES runs (id),
  state TEXT NOT NULL CHECK (state IN ('open', 'published', 'abandoned')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1)
) STRICT;

CREATE TABLE repository_changes (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'rchg_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  change_set_id TEXT NOT NULL REFERENCES change_sets (id),
  binding_id TEXT NOT NULL REFERENCES repository_bindings (id),
  workspace_id TEXT REFERENCES workspaces (id),
  base_commit TEXT,
  head_commit TEXT,
  branch TEXT NOT NULL,
  patch_artifact_id TEXT REFERENCES artifacts (id),
  pull_request_url TEXT,
  pull_request_state TEXT NOT NULL DEFAULT 'none' CHECK (pull_request_state IN ('none', 'draft', 'ready', 'merged', 'closed')),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  UNIQUE (change_set_id, binding_id)
) STRICT;

CREATE TABLE work_items (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 5) = 'work_' AND length(id) = 37 AND substr(id, 6) NOT GLOB '*[^0-9a-f]*'),
  kind TEXT NOT NULL,
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  state TEXT NOT NULL CHECK (state IN ('pending', 'claimed', 'done', 'failed', 'uncertain')),
  run_attempt_id TEXT REFERENCES run_attempts (id),
  controller_generation INTEGER CHECK (controller_generation >= 1),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at TEXT NOT NULL CHECK (available_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  last_error TEXT,
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  updated_at TEXT NOT NULL CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE mutation_receipts (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'mut_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  work_item_id TEXT NOT NULL REFERENCES work_items (id),
  target TEXT NOT NULL,
  operation TEXT NOT NULL,
  idempotency_key TEXT,
  state TEXT NOT NULL CHECK (state IN ('intended', 'confirmed', 'failed', 'uncertain')),
  request TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(request)),
  response TEXT CHECK (json_valid(response)),
  created_at TEXT NOT NULL CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  confirmed_at TEXT CHECK (confirmed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE observations (
  id TEXT PRIMARY KEY NOT NULL CHECK (substr(id, 1, 4) = 'obs_' AND length(id) = 36 AND substr(id, 5) NOT GLOB '*[^0-9a-f]*'),
  subject_type TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  source TEXT NOT NULL,
  observed_at TEXT NOT NULL CHECK (observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE INDEX change_sets_by_task ON change_sets (task_id);

CREATE INDEX work_items_ready ON work_items (available_at) WHERE state = 'pending';

CREATE INDEX mutation_receipts_by_work_item ON mutation_receipts (work_item_id);

CREATE INDEX observations_by_subject ON observations (subject_type, subject_id, observed_at);

CREATE TABLE record_events (
  sequence INTEGER PRIMARY KEY AUTOINCREMENT,
  id TEXT NOT NULL UNIQUE CHECK (substr(id, 1, 4) = 'evt_' AND length(id) = 36),
  aggregate_type TEXT NOT NULL CHECK (aggregate_type IN ('project', 'task', 'task_plan', 'run', 'workflow_execution', 'node', 'node_attempt', 'thread', 'provider_session', 'permission_request', 'attention_request', 'change_set', 'agent_installation', 'account_status')),
  aggregate_id TEXT NOT NULL,
  aggregate_revision INTEGER NOT NULL CHECK (aggregate_revision >= 1),
  type TEXT NOT NULL CHECK (type GLOB '[a-z]*.[a-z]*' AND type NOT GLOB '*[^a-z_.]*'),
  payload TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(payload)),
  actor_id TEXT NOT NULL REFERENCES actors (id),
  command_id TEXT CHECK (substr(command_id, 1, 4) = 'cmd_'),
  occurred_at TEXT NOT NULL CHECK (occurred_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE change_log (
  cursor INTEGER PRIMARY KEY AUTOINCREMENT,
  aggregate_type TEXT NOT NULL CHECK (aggregate_type IN ('project', 'task', 'task_plan', 'run', 'workflow_execution', 'node', 'node_attempt', 'thread', 'provider_session', 'permission_request', 'attention_request', 'change_set', 'agent_installation', 'account_status')),
  aggregate_id TEXT NOT NULL,
  revision INTEGER NOT NULL CHECK (revision >= 1),
  changed_at TEXT NOT NULL CHECK (changed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE TABLE command_receipts (
  command_id TEXT PRIMARY KEY NOT NULL CHECK (substr(command_id, 1, 4) = 'cmd_' AND length(command_id) = 36),
  command_type TEXT NOT NULL,
  schema_version INTEGER NOT NULL CHECK (schema_version >= 1),
  payload_digest TEXT NOT NULL CHECK (length(payload_digest) = 64 AND payload_digest NOT GLOB '*[^0-9a-f]*'),
  actor_id TEXT NOT NULL REFERENCES actors (id),
  device_id TEXT NOT NULL REFERENCES devices (id),
  aggregate_id TEXT,
  result TEXT NOT NULL CHECK (json_valid(result)),
  received_at TEXT NOT NULL CHECK (received_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'),
  completed_at TEXT NOT NULL CHECK (completed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z')
) STRICT;

CREATE INDEX record_events_by_aggregate ON record_events (aggregate_type, aggregate_id, sequence);
