import { at, id, index, json, oneOf, ref, revision, table } from './columns'

/** Agents on this device, who they are signed in as, their sessions and processes, and node attempts. */
export const agents: ReadonlyArray<string> = [
  table('agent_installations', [
    id('inst'),
    ref('device_id', 'devices'),
    'agent_id TEXT NOT NULL',
    'agent_version TEXT',
    'adapter_version TEXT',
    'protocol_version INTEGER',
    oneOf('status', ['supported', 'degraded', 'blocked', 'missing']),
    json('capabilities', { empty: '{}' }),
    at('probed_at'),
  ]),

  table('principals', [
    id('prin'),
    'agent_id TEXT NOT NULL',
    ref('device_id', 'devices'),
    'subject_hint TEXT NOT NULL',
    oneOf('auth_mode', ['vendor_cli', 'api_key', 'oauth', 'enterprise', 'workload']),
    at('observed_at'),
  ]),

  table('account_statuses', [
    id('acct'),
    ref('principal_id', 'principals'),
    oneOf('state', ['ok', 'warning', 'limited']),
    json('windows', { empty: '[]' }),
    oneOf('source', ['error', 'side_channel']),
    at('observed_at'),
  ]),

  table('provider_sessions', [
    id('sess'),
    ref('thread_id', 'threads'),
    'agent_id TEXT NOT NULL',
    'model TEXT',
    'effort TEXT',
    ref('principal_id', 'principals', { nullable: true }),
    ref('installation_id', 'agent_installations', { nullable: true }),
    'external_session_id TEXT',
    ref('run_attempt_id', 'run_attempts', { nullable: true }),
    'controller_generation INTEGER CHECK (controller_generation >= 1)',
    ref('brief_artifact_id', 'artifacts', { nullable: true }),
    oneOf('state', [
      'probing',
      'auth_required',
      'ready',
      'starting',
      'active',
      'waiting_approval',
      'completed',
      'cancelling',
      'cancelled',
      'lost',
      'reconciling',
      'uncertain',
      'failed',
      'superseded',
    ]),
    ref('superseded_by_session_id', 'provider_sessions', { nullable: true }),
    'last_event_sequence INTEGER NOT NULL DEFAULT 0 CHECK (last_event_sequence >= 0)',
    at('started_at'),
    at('ended_at', { nullable: true }),
    revision,
    "CHECK ((state = 'superseded') = (superseded_by_session_id IS NOT NULL))",
  ]),

  table('provider_events', [
    'session_id TEXT NOT NULL REFERENCES provider_sessions (id)',
    'sequence INTEGER NOT NULL CHECK (sequence >= 1)',
    oneOf('direction', ['in', 'out']),
    'method TEXT',
    json('payload'),
    at('received_at'),
    'PRIMARY KEY (session_id, sequence)',
  ]),

  table('processes', [
    id('proc'),
    ref('device_id', 'devices'),
    ref('provider_session_id', 'provider_sessions', { nullable: true }),
    ref('run_attempt_id', 'run_attempts', { nullable: true }),
    oneOf('purpose', ['agent', 'verify', 'setup', 'git', 'other']),
    'executable TEXT NOT NULL',
    'executable_version TEXT',
    'pid INTEGER NOT NULL CHECK (pid > 0)',
    'process_group_id INTEGER CHECK (process_group_id > 0)',
    json('args_redacted', { empty: '[]' }),
    'environment_digest TEXT',
    'controller_generation INTEGER CHECK (controller_generation >= 1)',
    oneOf('state', ['running', 'exited', 'killed', 'unknown']),
    at('started_at'),
    at('ended_at', { nullable: true }),
    'exit_code INTEGER',
    'signal TEXT',
  ]),

  table('node_attempts', [
    id('natt'),
    ref('node_id', 'nodes'),
    'attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1)',
    ref('run_attempt_id', 'run_attempts'),
    'controller_generation INTEGER NOT NULL CHECK (controller_generation >= 1)',
    ref('provider_session_id', 'provider_sessions', { nullable: true }),
    oneOf('state', [
      'ready',
      'admitted',
      'running',
      'waiting_attention',
      'verifying',
      'succeeded',
      'failed',
      'cancelling',
      'cancelled',
      'uncertain',
      'reconciling',
      'superseded',
    ]),
    json('input', { empty: '{}' }),
    json('output', { nullable: true }),
    ref('output_artifact_id', 'artifacts', { nullable: true }),
    'error_class TEXT',
    at('admitted_at'),
    at('started_at', { nullable: true }),
    at('ended_at', { nullable: true }),
    revision,
    'UNIQUE (node_id, attempt_number)',
  ]),

  index('account_statuses_by_principal', 'account_statuses (principal_id, observed_at)'),
  index('provider_sessions_by_thread', 'provider_sessions (thread_id)'),
  index('provider_sessions_by_run_attempt', 'provider_sessions (run_attempt_id)'),
  index('processes_by_session', 'processes (provider_session_id)'),
  index('processes_running', 'processes (state)', { where: "state = 'running'" }),
  index('node_attempts_by_session', 'node_attempts (provider_session_id)'),
  index('node_attempts_by_run_attempt', 'node_attempts (run_attempt_id)'),
]
