import { vocabulary } from './columns'

/*
 * Every vocabulary as a lookup table (vocab_<name>), so a new word is an
 * INSERT in a later migration rather than a table rebuild. The words are
 * written out here, not imported, so this migration never changes; a test
 * keeps them equal to @charrette/domain's lists.
 */
export const vocabularies: ReadonlyArray<string> = [
  ...vocabulary('actor_kind', ['person', 'agent', 'system']),
  ...vocabulary('repository_access', ['read', 'write', 'observe']),
  ...vocabulary('location_kind', ['existing', 'managed']),
  ...vocabulary('location_state', ['ready', 'needs_access', 'changed', 'unavailable']),
  ...vocabulary('artifact_kind', ['brief', 'message', 'transcript', 'patch', 'log', 'report', 'findings', 'summary', 'other']),
  ...vocabulary('sensitivity', ['normal', 'may_contain_secrets']),
  ...vocabulary('task_state', ['draft', 'open', 'done', 'abandoned']),
  ...vocabulary('plan_state', ['proposed', 'accepted', 'replaced', 'declined']),
  ...vocabulary('run_state', ['admitted', 'running', 'suspended', 'succeeded', 'failed', 'cancelled']),
  ...vocabulary('run_attempt_state', ['active', 'succeeded', 'failed', 'cancelled', 'interrupted']),
  ...vocabulary('workspace_state', ['preparing', 'ready', 'published', 'cleaned', 'failed']),
  ...vocabulary('snapshot_reason', ['node_started', 'node_ended', 'switch', 'interrupt']),
  ...vocabulary('execution_state', ['running', 'succeeded', 'failed', 'cancelled']),
  ...vocabulary('graph_revision_cause', ['materialized', 'patch']),
  ...vocabulary('node_type', [
    'deterministic_action',
    'agent',
    'integration',
    'human_decision',
    'condition',
    'bounded_map',
    'join',
    'verification',
    'compensation',
    'subworkflow',
    'bounded_loop',
  ]),
  ...vocabulary('node_state', ['pending', 'ready', 'running', 'succeeded', 'failed', 'skipped', 'cancelled', 'uncertain']),
  ...vocabulary('node_attempt_state', [
    'ready',
    'admitted',
    'running',
    'waiting_attention',
    'verifying',
    'succeeded',
    'failed',
    'cancelling',
    'cancelled',
    'uncertain',
    'reconciling',
    'held',
    'superseded',
  ]),
  ...vocabulary('hold_reason', ['usage_limit', 'agent_unavailable']),
  ...vocabulary('thread_kind', ['coordinator', 'task', 'step']),
  ...vocabulary('thread_item_kind', ['user_message', 'agent_message', 'agent_thought', 'tool_call', 'plan', 'step_result', 'notice']),
  ...vocabulary('input_disposition', ['after_current', 'interrupt_and_continue', 'supersede_pending', 'cancel_run']),
  ...vocabulary('user_input_state', ['queued', 'delivered', 'superseded']),
  ...vocabulary('turn_delivery_state', ['pending', 'delivered', 'completed', 'interrupted', 'interruption_uncertain', 'failed']),
  ...vocabulary('installation_status', ['supported', 'degraded', 'blocked', 'missing']),
  ...vocabulary('auth_mode', ['vendor_cli', 'api_key', 'oauth', 'enterprise', 'workload']),
  ...vocabulary('account_state', ['ok', 'warning', 'limited']),
  ...vocabulary('account_status_source', ['error', 'side_channel']),
  ...vocabulary('provider_session_state', [
    'probing',
    'auth_required',
    'ready',
    'starting',
    'active',
    'waiting_approval',
    'completed',
    'cancelling',
    'cancelled',
    'lost',
    'reconciling',
    'uncertain',
    'failed',
    'superseded',
  ]),
  ...vocabulary('process_purpose', ['agent', 'verify', 'setup', 'git', 'other']),
  ...vocabulary('process_state', ['launching', 'running', 'exited', 'killed', 'unknown']),
  ...vocabulary('tool_kind', ['read', 'edit', 'delete', 'move', 'search', 'execute', 'think', 'fetch', 'switch_mode', 'other']),
  ...vocabulary('permission_request_state', ['open', 'decided', 'cancelled']),
  ...vocabulary('attention_kind', ['permission', 'question', 'stuck', 'plan', 'graph_patch', 'usage_limit', 'review_disagreement']),
  ...vocabulary('attention_state', ['open', 'answered', 'expired', 'withdrawn']),
  ...vocabulary('finding_severity', ['blocking', 'major', 'minor', 'nit']),
  ...vocabulary('finding_state', ['open', 'fixed', 'set_aside', 'dismissed']),
  ...vocabulary('decision_outcome', ['allow', 'reject', 'answer', 'fix', 'dismiss']),
  ...vocabulary('decision_scope', ['once', 'rule']),
  ...vocabulary('change_set_state', ['open', 'published', 'abandoned']),
  ...vocabulary('pull_request_state', ['none', 'draft', 'ready', 'merged', 'closed']),
  ...vocabulary('work_item_state', ['pending', 'claimed', 'done', 'failed', 'uncertain']),
  ...vocabulary('mutation_state', ['intended', 'confirmed', 'failed', 'uncertain']),
  ...vocabulary('aggregate_type', [
    'project',
    'task',
    'task_plan',
    'run',
    'run_attempt',
    'workspace',
    'workflow_execution',
    'node',
    'node_attempt',
    'thread',
    'user_input',
    'turn_delivery',
    'provider_session',
    'permission_request',
    'attention_request',
    'decision',
    'finding',
    'change_set',
    'mutation_receipt',
    'agent_installation',
    'account_status',
  ]),
]
