import { at, flag, id, index, json, oneOf, ref, revision, sha256, table } from './columns'

/** Tasks, plans and runs; workspaces; workflow definitions and executions. */
export const work: ReadonlyArray<string> = [
  table('tasks', [
    id('task'),
    ref('project_id', 'projects'),
    'title TEXT NOT NULL',
    "description TEXT NOT NULL DEFAULT ''",
    "slug TEXT NOT NULL CHECK (slug <> '' AND slug NOT GLOB '*[^a-z0-9-]*')",
    oneOf('state', ['draft', 'open', 'done', 'abandoned']),
    ref('created_by_actor_id', 'actors'),
    at('created_at'),
    at('settled_at', { nullable: true }),
    revision,
    'UNIQUE (project_id, slug)',
  ]),

  table('task_repository_requirements', [
    id('req'),
    ref('task_id', 'tasks'),
    ref('binding_id', 'repository_bindings'),
    oneOf('access', ['read', 'write', 'observe']),
    json('allowed_roots', { empty: '[]' }),
    'base_ref TEXT',
    flag('required', 1),
    'UNIQUE (task_id, binding_id)',
  ]),

  table('workflow_definitions', [id('wdef'), 'name TEXT NOT NULL UNIQUE', at('created_at'), at('retired_at', { nullable: true })]),

  table('workflow_versions', [
    id('wver'),
    ref('definition_id', 'workflow_definitions'),
    'version INTEGER NOT NULL CHECK (version >= 1)',
    sha256('content_hash'),
    json('definition'),
    at('created_at'),
    'UNIQUE (definition_id, version)',
  ]),

  table('task_plans', [
    id('plan'),
    ref('task_id', 'tasks'),
    ref('workflow_version_id', 'workflow_versions'),
    json('parameters', { empty: '{}' }),
    ref('proposed_by_actor_id', 'actors'),
    oneOf('state', ['proposed', 'accepted', 'replaced', 'declined']),
    at('proposed_at'),
    at('starts_at', { nullable: true }),
    at('decided_at', { nullable: true }),
    revision,
  ]),

  table('runs', [
    id('run'),
    ref('task_id', 'tasks'),
    ref('plan_id', 'task_plans', { nullable: true }),
    ref('workflow_version_id', 'workflow_versions'),
    ref('policy_id', 'policies'),
    json('parameters', { empty: '{}' }),
    json('budget', { empty: '{}' }),
    oneOf('state', ['admitted', 'running', 'suspended', 'succeeded', 'failed', 'cancelled']),
    'end_reason TEXT',
    at('created_at'),
    at('ended_at', { nullable: true }),
    revision,
  ]),

  table('run_attempts', [
    id('ratt'),
    ref('run_id', 'runs'),
    'attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1)',
    'controller_generation INTEGER NOT NULL DEFAULT 1 CHECK (controller_generation >= 1)',
    oneOf('state', ['active', 'succeeded', 'failed', 'cancelled', 'interrupted']),
    at('started_at'),
    at('ended_at', { nullable: true }),
    'UNIQUE (run_id, attempt_number)',
  ]),

  table('workspace_sets', [
    id('wset'),
    ref('run_attempt_id', 'run_attempts'),
    'root_path TEXT NOT NULL',
    oneOf('state', ['preparing', 'ready', 'published', 'cleaned', 'failed']),
    at('created_at'),
    at('cleaned_at', { nullable: true }),
  ]),

  table('workspaces', [
    id('ws'),
    ref('workspace_set_id', 'workspace_sets'),
    ref('binding_id', 'repository_bindings'),
    'path TEXT NOT NULL',
    'base_ref TEXT NOT NULL',
    'base_commit TEXT',
    'branch TEXT NOT NULL',
    oneOf('state', ['preparing', 'ready', 'published', 'cleaned', 'failed']),
    at('created_at'),
    at('cleaned_at', { nullable: true }),
    'UNIQUE (workspace_set_id, binding_id)',
  ]),

  table('workflow_executions', [
    id('wexe'),
    'run_id TEXT NOT NULL UNIQUE REFERENCES runs (id)',
    ref('workflow_version_id', 'workflow_versions'),
    'graph_revision INTEGER NOT NULL DEFAULT 1 CHECK (graph_revision >= 1)',
    oneOf('state', ['running', 'succeeded', 'failed', 'cancelled']),
    at('created_at'),
    at('ended_at', { nullable: true }),
    revision,
  ]),

  table('graph_patches', [
    id('patch'),
    ref('execution_id', 'workflow_executions'),
    'expected_revision INTEGER NOT NULL CHECK (expected_revision >= 1)',
    json('operations', { empty: '[]' }),
    json('authority_delta', { empty: '{}' }),
    json('budget_delta', { empty: '{}' }),
    ref('rationale_artifact_id', 'artifacts', { nullable: true }),
    ref('proposed_by_actor_id', 'actors'),
    oneOf('state', ['proposed', 'held', 'accepted', 'rejected', 'undone']),
    at('created_at'),
    at('hold_until', { nullable: true }),
    at('decided_at', { nullable: true }),
  ]),

  table('execution_graph_revisions', [
    'execution_id TEXT NOT NULL REFERENCES workflow_executions (id)',
    'revision INTEGER NOT NULL CHECK (revision >= 1)',
    json('graph'),
    oneOf('cause', ['materialized', 'patch']),
    ref('patch_id', 'graph_patches', { nullable: true }),
    at('created_at'),
    'PRIMARY KEY (execution_id, revision)',
    "CHECK ((cause = 'patch') = (patch_id IS NOT NULL))",
  ]),

  table('nodes', [
    id('node'),
    ref('execution_id', 'workflow_executions'),
    'node_key TEXT NOT NULL',
    'iteration INTEGER NOT NULL DEFAULT 0 CHECK (iteration >= 0)',
    oneOf('type', [
      'deterministic_action',
      'agent',
      'integration',
      'human_decision',
      'condition',
      'bounded_map',
      'join',
      'verification',
      'compensation',
      'subworkflow',
      'bounded_loop',
    ]),
    'added_in_revision INTEGER NOT NULL CHECK (added_in_revision >= 1)',
    json('config', { empty: '{}' }),
    oneOf('state', ['pending', 'ready', 'running', 'succeeded', 'failed', 'skipped', 'cancelled', 'uncertain']),
    at('created_at'),
    revision,
    'UNIQUE (execution_id, node_key, iteration)',
  ]),

  index('tasks_by_project', 'tasks (project_id, state)'),
  index('task_plans_by_task', 'task_plans (task_id)'),
  index('runs_by_task', 'runs (task_id)'),
  index('workspace_sets_by_run_attempt', 'workspace_sets (run_attempt_id)'),
  index('graph_patches_by_execution', 'graph_patches (execution_id)'),
]
