export { authorizationOf, type AdapterOptions, type Credential } from './credential'
export * from './errors'
export { makeGitHub } from './github'
export { type Fetch, makeHttp } from './http'
export { makeLinear } from './linear'
export { HOSTED, type KnownHosts, type LinkRef, linksIn, parseLink, parseRemote, type RemoteRef } from './links'
export * from './model'
export { available, type ProductInfo, products } from './products'
export * from './signIn'
