import { existsSync } from 'node:fs'

import { Effect } from 'effect'
import { SqlClient } from 'effect/sql'

import { GitFailed } from './errors'
import { commitRecord, commitsOf, git, gitOutcome, recommit, signsCommits } from './git'
import { timestamp } from './records'

/*
 * Who the work Althar sends out is credited to (docs/architecture/06). The
 * person is the author of every commit. The agents' own credit lines, the
 * co-author trailers and "Generated with" footers they add, never leave the
 * Mac: before Althar pushes a task's branch, or merges it here, it makes
 * again each commit of the branch that is nowhere else yet, with those lines
 * taken out. Unless the person turned it off, Althar adds itself as
 * co-author instead: its GitHub account, by that account's private address,
 * so the host shows its picture.
 *
 * An agent's line is known by its name and its address together: a name
 * that starts with an agent's or a model's (Claude, Codex, Copilot, or the
 * name of any agent Althar runs) at a machine's address (a noreply one, a
 * bot's, an AI company's). A person called Claude, at their own address or
 * their GitHub one, is kept.
 *
 * What was sent is never made again: Althar remembers each commit it makes
 * again and what from, so it comes out the same every time, and asks the
 * remote where its branch is before pushing. Only the branch's own line of commits is made again; what a merge
 * brought in from elsewhere stays as it was.
 */

/** Althar's GitHub account, by its private address, as a commit names a co-author. */
export const ALTHAR = { name: 'Althar', email: '337922799+AltharAi@users.noreply.github.com' } as const

/** The trailer Althar adds to each commit while it is co-author. */
export const coAuthorLine = `Co-authored-by: ${ALTHAR.name} <${ALTHAR.email}>`

/** How agents and models name themselves in credit lines: a line's name starts with one. */
const AGENT_NAMES = [
  'althar',
  'amp',
  'aider',
  'augment',
  'chatgpt',
  'claude',
  'cline',
  'codex',
  'copilot',
  'cursor',
  'devin',
  'droid',
  'gemini',
  'github copilot',
  'glm',
  'goose',
  'gpt',
  'grok',
  'jules',
  'junie',
  'kimi',
  'kiro',
  'openai',
  'opencode',
  'qwen',
  'roo',
  'windsurf',
]

/** The names agents sign footers with, whole: "Generated by Claude Code", never "Created by Claude Monet". */
const AGENT_PRODUCTS = new Set([
  'aider',
  'amp',
  'claude',
  'claude code',
  'cline',
  'codex',
  'codex cli',
  'copilot',
  'cursor',
  'cursor agent',
  'devin',
  'gemini',
  'gemini cli',
  'github copilot',
  'goose',
  'jules',
  'junie',
  'opencode',
  'qwen code',
  'windsurf',
])

/** Agents' own addresses, which say nothing of a reply: a person at the same company has their own. */
const AGENT_ADDRESSES = new Set(['codex@openai.com', 'cursoragent@cursor.com', 'aider@aider.chat'])

/** GitHub's private addresses: a person's as well as a bot's, told apart by the account. */
const GITHUB_PRIVATE = '@users.noreply.github.com'

/** Agents' own GitHub accounts, which aren't bots by name: Copilot's. */
const AGENT_LOGINS = new Set(['copilot', 'claude', 'codex', 'cursoragent', 'devin-ai-integration'])

/** A bot named for the agent it is: google-labs-jules[bot], copilot-swe-agent[bot]; not campaign-roomba[bot]. */
const agentBot = (name: string, agents: ReadonlyArray<string>) => {
  const said = name.trim().toLowerCase()
  if (!said.endsWith('[bot]')) return false
  const words = said.slice(0, -'[bot]'.length).split(/[-_\s]+/)
  return words.some((word) => lowered(agents).includes(word))
}

/** The trailers that credit someone with a commit. */
const CREDIT_KEYS = new Set(['co-authored-by', 'generated-by', 'assisted-by'])

const TRAILER = /^([A-Za-z][A-Za-z0-9-]*):[ \t]*(.*)$/
const PERSON = /^(.*?)\s*<([^<>]*)>\s*$/
/**
 * A footer an agent signs with, alone on its line: 🤖 Generated with [Claude
 * Code](https://claude.com/claude-code). The name ends the line, or its link
 * does, so a sentence that goes on is a person's.
 */
const FOOTER = /^([^\p{L}\p{N}]*)(?:generated|created|made)\s+(?:with|by|using)\s+\[?([^\]()[]+?)\]?(?:\([^()\s]*\))?[\s.!]*$/iu

const lowered = (agents: ReadonlyArray<string>) => [...AGENT_NAMES, ...agents.map((agent) => agent.toLowerCase())]

const startsWithAgent = (name: string, agents: ReadonlyArray<string>) => {
  const said = name.trim().toLowerCase()
  return lowered(agents).some((agent) => said === agent || (said.startsWith(agent) && /[\s\-(.:/0-9[]/.test(said.charAt(agent.length))))
}

const machineAddress = (email: string, agents: ReadonlyArray<string>) => {
  const address = email.trim().toLowerCase()
  // On GitHub, a bot's account ends in [bot]; an agent's own account has its name (Copilot); anyone else is a person.
  if (address.endsWith(GITHUB_PRIVATE)) {
    const login = address.slice(0, -GITHUB_PRIVATE.length).replace(/^\d+\+/, '')
    return login.endsWith('[bot]') || AGENT_LOGINS.has(login) || agents.some((agent) => agent.toLowerCase() === login)
  }
  return address.includes('noreply') || address.includes('no-reply') || AGENT_ADDRESSES.has(address)
}

/** Whether a line of a message credits an agent, or Althar: a trailer naming one, or an agent's footer. */
const creditLine = (line: string, agents: ReadonlyArray<string>) => {
  // Trailers and footers start their line: anything indented is quoted, or code.
  if (/^\s/.test(line)) return false
  const trailer = TRAILER.exec(line.trimEnd())
  if (trailer !== null && CREDIT_KEYS.has((trailer[1] ?? '').toLowerCase())) {
    const value = trailer[2] ?? ''
    const person = PERSON.exec(value)
    if (person === null) return startsWithAgent(value, agents)
    const [, name = '', email = ''] = person
    if (email.trim().toLowerCase() === ALTHAR.email.toLowerCase()) return true
    // A bot named for what it is: google-labs-jules[bot], copilot-swe-agent[bot].
    return agentBot(name, agents) || (startsWithAgent(name, agents) && machineAddress(email, agents))
  }
  const footer = FOOTER.exec(line.trimEnd())
  if (footer === null) return false
  const [, before = '', name = ''] = footer
  const said = name.trim().toLowerCase()
  // An agent's own name, whole; or one after its mark (🤖), as only an agent signs.
  return (
    AGENT_PRODUCTS.has(said) ||
    agents.some((agent) => agent.toLowerCase() === said) ||
    (before.trim() !== '' && startsWithAgent(said, agents))
  )
}

/**
 * Lines without the agents' credit. Where one goes, the blank line it leaves
 * goes with it; elsewhere the text is as written, and nothing in a fenced
 * block is touched.
 */
const withoutCredit = (lines: ReadonlyArray<string>, agents: ReadonlyArray<string>) => {
  const kept: Array<string> = []
  const fence = /^\s*(```|~~~)/
  // A fence never closed fences nothing: it is text, not a block.
  const fences = lines.filter((line) => fence.test(line)).length % 2 === 0
  let fenced = false
  let removed = false
  let any = false
  for (const line of lines) {
    if (fences && fence.test(line)) fenced = !fenced
    if (!fenced && creditLine(line, agents)) {
      removed = true
      any = true
      continue
    }
    const blank = line.trim() === ''
    if (blank && removed && (kept.length === 0 || kept.at(-1)?.trim() === '')) continue
    if (!blank) removed = false
    kept.push(line)
  }
  if (any) while (kept.length > 0 && kept.at(-1)?.trim() === '') kept.pop()
  return { kept, any }
}

/**
 * A commit message as Althar sends it: the agents' credit lines out, and
 * Althar's trailer last when it is co-author, in the message's own trailers
 * where it ends with some. A message that needs nothing comes back as it was.
 */
export const creditedMessage = (message: string, options: { readonly coAuthor: boolean; readonly agents: ReadonlyArray<string> }) => {
  const { kept, any } = withoutCredit(message.split('\n'), options.agents)
  while (kept.length > 0 && kept.at(-1)?.trim() === '') kept.pop()
  // A message that was all credit is left alone rather than emptied.
  if (kept.length === 0) return message
  if (!any && !options.coAuthor) return message
  if (options.coAuthor) {
    const blank = kept.findLastIndex((line) => line.trim() === '')
    const trailers = blank > 0 && kept.slice(blank + 1).every((line) => TRAILER.test(line.trimEnd()))
    kept.push(...(trailers ? [coAuthorLine] : ['', coAuthorLine]))
  }
  const credited = `${kept.join('\n')}\n`
  return credited.trimEnd() === message.trimEnd() ? message : credited
}

/** A pull request's description, or any text Althar sends, without the agents' credit lines. */
export const withoutAgentCredit = (text: string, agents: ReadonlyArray<string>) => {
  const { kept, any } = withoutCredit(text.split('\n'), agents)
  return !any || kept.length === 0 ? text : kept.join('\n')
}

/* ---- a branch ---------------------------------------------------------------------- */

/** A commit Althar made again: the agent's, and Althar's of it. */
export interface Made {
  readonly original: string
  readonly credited: string
}

/**
 * What Althar remembers of the commits it made again: `recall` says what
 * each original became, and that each credited one is done; `remember` keeps
 * what it just made, before anything is sent, so the same commit comes out
 * the same way next time, signed or not, whatever the setting says by then.
 */
export interface Memory {
  readonly recall: (commits: ReadonlyArray<string>) => Effect.Effect<ReadonlyMap<string, string>>
  readonly remember: (made: ReadonlyArray<Made>) => Effect.Effect<void>
}

/** Remembers nothing: for a branch made again only once. */
export const forgetful: Memory = { recall: () => Effect.succeed(new Map()), remember: () => Effect.void }

export interface CreditOptions {
  /** Commits already sent, which stay as they are, with all before them: the remote's tip, the head last pushed. */
  readonly known: ReadonlyArray<string | null>
  /** What is about to be sent: a commit on the branch, or one from before it was credited that the person saw. */
  readonly head: string
  readonly coAuthor: boolean
  readonly agents: ReadonlyArray<string>
  readonly memory: Memory
}

/** A branch credited: what `head` became, what was made again, and the move of the branch onto it once it went. */
export interface Credited {
  readonly head: string
  readonly made: ReadonlyArray<Made>
  readonly settle: Effect.Effect<void>
}

const identity = (head: string): Credited => ({ head, made: [], settle: Effect.void })

/**
 * The commits of a worktree's branch up to `head` that are nowhere else yet,
 * made again credited as `creditedMessage` says, and remembered, without
 * moving the branch: what `head` became, what was made, and a way to move the
 * branch onto them once it is sent.
 *
 * Only the branch's own line is made again (its first parents); what a merge
 * brought in keeps its commits. A commit sent before goes as it went; one
 * remembered goes as it was made then; anything else is made from its tree,
 * parents, people, dates and message alone, so it comes out the same again.
 * A commit that making again would spoil (another encoding, a signed tag
 * merged) leaves the whole branch as it is. So does a branch that isn't
 * there.
 */
export const creditBranch = (cwd: string, branch: string, options: CreditOptions): Effect.Effect<Credited, GitFailed> =>
  Effect.gen(function* () {
    const [tip, head] = yield* commitsOf(cwd, [`refs/heads/${branch}`, options.head])
    if (tip === null || tip === undefined || head === null || head === undefined) return identity(options.head)
    const known = (yield* commitsOf(
      cwd,
      options.known.filter((commit) => commit !== null),
    )).filter((commit) => commit !== null)
    // What any other branch, tag or remote has is someone else's already.
    const not = ['--not', `--exclude=${branch}`, '--branches', '--remotes', '--tags', ...known]
    const lineOf = (from: ReadonlyArray<string>) =>
      Effect.map(git(cwd, 'rev-list', '--reverse', '--topo-order', '--first-parent', ...from, ...not), (listed) =>
        listed.split('\n').filter((line) => line !== ''),
      )
    const listed = [...new Set([...(yield* lineOf([head])), ...(yield* lineOf([tip]))])]
    if (listed.length === 0) return identity(head)
    const remembered = yield* options.memory.recall(listed)
    const sign = yield* signsCommits(cwd)
    // Agents commit as the person; a commit made as anyone else came from elsewhere, and stays theirs.
    const person = /<([^<>]*)>/.exec((yield* gitOutcome(cwd, 'var', 'GIT_COMMITTER_IDENT')).stdout)?.[1]?.toLowerCase() ?? ''
    const became = new Map<string, string>()
    for (const commit of listed) {
      const was = remembered.get(commit)
      if (was !== undefined && (yield* commitsOf(cwd, [was]))[0] !== null) {
        became.set(commit, was)
        continue
      }
      const record = yield* commitRecord(cwd, commit)
      const parents = record.parents.map((parent) => became.get(parent) ?? parent)
      const message = creditedMessage(record.message, options)
      const same = message === record.message && parents.every((parent, at) => parent === record.parents[at])
      if (same) {
        became.set(commit, commit)
        continue
      }
      const theirs = person === '' || ![record.author.email, record.committer.email].some((email) => email.toLowerCase() === person)
      if (theirs && parents.every((parent, at) => parent === record.parents[at])) {
        became.set(commit, commit)
        continue
      }
      // Someone else's commit that would have to move, or one that making again would spoil: the branch goes as it is.
      if (theirs || record.keeps) return identity(head)
      // Signed again where git signs commits here, or where it was signed.
      became.set(commit, yield* recommit(cwd, record, parents, message, sign || record.signed))
    }
    /** What a commit became: itself where it wasn't made again, or was sent before. */
    const of = (commit: string) => became.get(commit) ?? commit
    const to = of(tip)
    const made = listed.flatMap((commit) =>
      of(commit) === commit || remembered.has(commit) ? [] : [{ original: commit, credited: of(commit) }],
    )
    yield* options.memory.remember(made)
    const move = (from: string, onto: string) =>
      gitOutcome(cwd, 'update-ref', '-m', 'Althar: credit', `refs/heads/${branch}`, onto, from).pipe(
        Effect.map((outcome) => outcome.code === 0),
      )
    return {
      head: of(head),
      made,
      /**
       * Moves the branch onto its credited commits, only from the commit it
       * was on when read. Where an agent committed meanwhile, its commits are
       * credited onto what was sent, once; if the branch moves again, it
       * stays, and the next send does it.
       */
      settle: Effect.gen(function* () {
        if (to === tip || !(yield* settled(cwd, branch))) return
        if (yield* move(tip, to)) return
        // An agent committed meanwhile: its commits go onto what was sent, as the next send would make them.
        const [now] = yield* commitsOf(cwd, [`refs/heads/${branch}`])
        if (now === null || now === undefined) return
        const again = yield* creditBranch(cwd, branch, { ...options, head: now })
        if (again.head !== now && (yield* settled(cwd, branch))) yield* move(now, again.head)
      }).pipe(Effect.ignore),
    }
  })

/**
 * Whether the worktree is still, on its branch, so moving the branch takes
 * nothing from under it: no rebase, merge, cherry-pick or revert under way,
 * and HEAD the branch by name.
 */
const settled = (cwd: string, branch: string) =>
  Effect.gen(function* () {
    const on = yield* gitOutcome(cwd, 'symbolic-ref', '-q', 'HEAD')
    if (on.stdout !== `refs/heads/${branch}`) return false
    for (const under of ['rebase-merge', 'rebase-apply', 'MERGE_HEAD', 'CHERRY_PICK_HEAD', 'REVERT_HEAD']) {
      const path = (yield* gitOutcome(cwd, 'rev-parse', '--path-format=absolute', '--git-path', under)).stdout
      if (path !== '' && existsSync(path)) return false
    }
    return true
  })

/* ---- what was made ----------------------------------------------------------------- */

/** What Althar remembers making of some commits (`Memory.recall`), from the profile. */
export const recallMade: (commits: ReadonlyArray<string>) => Effect.Effect<ReadonlyMap<string, string>, never, SqlClient.SqlClient> = (
  commits,
) =>
  Effect.gen(function* () {
    const sql = yield* SqlClient.SqlClient
    const rows = yield* sql<{ original: string; credited: string }>`
      SELECT original, credited FROM credited_commits WHERE original IN ${sql.in(commits)}
      UNION SELECT credited, credited FROM credited_commits WHERE credited IN ${sql.in(commits)}`
    return new Map(rows.map((row) => [row.original, row.credited]))
  }).pipe(Effect.orElseSucceed(() => new Map<string, string>()))

/** Remembers what Althar made (`Memory.remember`) in the profile. Not remembered, it still goes. */
export const rememberMade = (made: ReadonlyArray<Made>) =>
  Effect.gen(function* () {
    if (made.length === 0) return
    const sql = yield* SqlClient.SqlClient
    const at = yield* timestamp
    for (const one of made)
      yield* sql`INSERT INTO credited_commits ${sql.insert({ original: one.original, credited: one.credited, madeAt: at })} ON CONFLICT (original) DO NOTHING`
  }).pipe(Effect.ignore)

/* ---- the setting ------------------------------------------------------------------ */

const CO_AUTHOR = 'co_author'

/** Whether Althar is co-author of what it sends: on, unless the person turned it off. */
export const coAuthorOn = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient
  const [row] = yield* sql<{ value: string }>`SELECT value FROM settings WHERE key = ${CO_AUTHOR}`
  return row?.value !== 'off'
})

/** Turns Althar's co-authoring on, which is its default and keeps no row, or off. */
export const setCoAuthor = (on: boolean) =>
  Effect.gen(function* () {
    const sql = yield* SqlClient.SqlClient
    if (on) return yield* sql`DELETE FROM settings WHERE key = ${CO_AUTHOR}`.pipe(Effect.asVoid)
    const at = yield* timestamp
    yield* sql`
      INSERT INTO settings ${sql.insert({ key: CO_AUTHOR, value: 'off', updatedAt: at })}
      ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`
  })
