import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { assert, describe, expect, it } from '@effect/vitest'
import { Effect, Layer } from 'effect'
import { SqlClient } from 'effect/sql'

import * as Database from '../src/Database'
import { canonicalJson, sha256Hex } from '../src/canonicalJson'
import { migrations } from '../src/migrations'
import { checksums } from '../src/migrations/checksums'
import { InMemory } from './support'

const schemaSql = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient
  const rows = yield* sql<{ sql: string }>`
    SELECT sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY rowid`
  return rows.map((row) => `${row.sql};`).join('\n\n')
})

describe('schema', () => {
  it.effect('creates every table as STRICT', () =>
    Effect.gen(function* () {
      const sql = yield* SqlClient.SqlClient
      const tables = yield* sql<{ name: string; sql: string }>`
        SELECT name, sql FROM sqlite_schema WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name <> 'schema_migrations'`
      assert.isAbove(tables.length, 40)
      for (const table of tables) assert.isTrue(table.sql.endsWith(') STRICT'), `${table.name} is not STRICT`)
    }).pipe(Effect.provide(InMemory)),
  )

  it.effect('matches schema.sql, the readable copy of the whole schema', () =>
    Effect.gen(function* () {
      const text = yield* schemaSql
      yield* Effect.promise(() =>
        expect(`-- Generated by tests/schema.test.ts from the migrations. Do not edit.\n\n${text}\n`).toMatchFileSnapshot('../schema.sql'),
      )
    }).pipe(Effect.provide(InMemory)),
  )

  it('never changes a released migration', () => {
    const actual = Object.fromEntries(migrations.map((migration) => [migration.key, sha256Hex(canonicalJson(migration.statements))]))
    assert.deepStrictEqual(
      actual,
      checksums,
      'A released migration changed. Add a new migration instead; for a new migration, add its checksum to src/migrations/checksums.ts.',
    )
  })

  it.effect('runs each migration once, with foreign keys on and WAL for a file', () =>
    Effect.gen(function* () {
      const directory = mkdtempSync(join(tmpdir(), 'charrette-schema-'))
      const filename = join(directory, 'profile.sqlite')
      const inspect = Effect.gen(function* () {
        const sql = yield* SqlClient.SqlClient
        const [journal] = yield* sql<{ journalMode: string }>`PRAGMA journal_mode`
        const [foreignKeys] = yield* sql<{ foreignKeys: number }>`PRAGMA foreign_keys`
        const applied = yield* sql<{ migrationId: number }>`SELECT migration_id FROM schema_migrations`
        return { journal: journal?.journalMode, foreignKeys: foreignKeys?.foreignKeys, applied: applied.length }
      })
      try {
        const first = yield* Effect.provide(inspect, Layer.fresh(Database.layer({ filename })))
        const second = yield* Effect.provide(inspect, Layer.fresh(Database.layer({ filename })))
        assert.deepStrictEqual(first, { journal: 'wal', foreignKeys: 1, applied: migrations.length })
        assert.deepStrictEqual(second, first)
      } finally {
        rmSync(directory, { recursive: true, force: true })
      }
    }),
  )
})
