import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { assert, describe, expect, it } from '@effect/vitest'
import { Effect, Layer } from 'effect'
import { SqlClient } from 'effect/sql'

import { canonicalJson, sha256Hex } from '../src/canonicalJson'
import * as Database from '../src/Database'
import { ForeignKeyViolations } from '../src/Database'
import { migrations } from '../src/migrations'
import { checksums } from '../src/migrations/checksums'
import { InMemory } from './support'

/** The schema as SQL, then each vocabulary's words, which live in rows. */
const readableSchema = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient
  const objects = yield* sql<{ name: string; sql: string }>`
    SELECT name, sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY rowid`
  const vocabularies: Array<string> = []
  for (const object of objects) {
    if (!object.name.startsWith('vocab_') || object.sql.startsWith('CREATE INDEX')) continue
    const words = yield* sql<{ word: string }>`SELECT word FROM ${sql(object.name)} ORDER BY rowid`
    vocabularies.push(`-- ${object.name.replace('vocab_', '')}: ${words.map((row) => row.word).join(', ')}`)
  }
  const schema = objects.filter((object) => !object.name.startsWith('vocab_')).map((object) => `${object.sql};`)
  return [
    '-- Generated by tests/schema.test.ts from the migrations. Do not edit.',
    '',
    '-- Vocabularies. Each is a table, vocab_<name> (word TEXT PRIMARY KEY), holding these words:',
    ...vocabularies,
    '',
    schema.join('\n\n'),
    '',
  ].join('\n')
})

const withFile = <A, E, R>(use: (filename: string) => Effect.Effect<A, E, R>) =>
  Effect.acquireUseRelease(
    Effect.sync(() => mkdtempSync(join(tmpdir(), 'althar-schema-'))),
    (directory) => use(join(directory, 'profile.sqlite')),
    (directory) => Effect.sync(() => rmSync(directory, { recursive: true, force: true })),
  )

describe('schema', () => {
  it.effect('creates every table as STRICT', () =>
    Effect.gen(function* () {
      const sql = yield* SqlClient.SqlClient
      const tables = yield* sql<{ name: string; sql: string }>`
        SELECT name, sql FROM sqlite_schema WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name <> 'schema_migrations'`
      assert.isAbove(tables.length, 80)
      for (const table of tables) assert.isTrue(table.sql.endsWith(') STRICT'), `${table.name} is not STRICT`)
    }).pipe(Effect.provide(InMemory)),
  )

  it.effect('matches schema.sql, the readable copy of the whole schema', () =>
    Effect.gen(function* () {
      const text = yield* readableSchema
      yield* Effect.promise(() => expect(text).toMatchFileSnapshot('../schema.sql'))
    }).pipe(Effect.provide(InMemory)),
  )

  it('never changes a released migration', () => {
    const actual = Object.fromEntries(migrations.map((migration) => [migration.key, sha256Hex(canonicalJson(migration.statements))]))
    assert.deepStrictEqual(
      actual,
      checksums,
      'A released migration changed. Add a new migration instead; for a new migration, add its checksum to src/migrations/checksums.ts.',
    )
  })

  it.effect('runs each migration once, with foreign keys on and WAL for a file', () =>
    withFile((filename) =>
      Effect.gen(function* () {
        const inspect = Effect.gen(function* () {
          const sql = yield* SqlClient.SqlClient
          const [journal] = yield* sql<{ journalMode: string }>`PRAGMA journal_mode`
          const [foreignKeys] = yield* sql<{ foreignKeys: number }>`PRAGMA foreign_keys`
          const applied = yield* sql<{ migrationId: number }>`SELECT migration_id FROM schema_migrations`
          return { journal: journal?.journalMode, foreignKeys: foreignKeys?.foreignKeys, applied: applied.length }
        })
        const first = yield* Effect.provide(inspect, Layer.fresh(Database.layer({ filename })))
        const second = yield* Effect.provide(inspect, Layer.fresh(Database.layer({ filename })))
        assert.deepStrictEqual(first, { journal: 'wal', foreignKeys: 1, applied: migrations.length })
        assert.deepStrictEqual(second, first)
      }),
    ),
  )

  it.effect(
    'lets one runtime at a time open a file',
    () =>
      withFile((filename) =>
        Effect.gen(function* () {
          const open = Effect.gen(function* () {
            const sql = yield* SqlClient.SqlClient
            yield* sql`SELECT 1`
          })
          yield* Effect.scoped(
            Effect.gen(function* () {
              yield* Layer.build(Layer.fresh(Database.layer({ filename })))
              const second = yield* Effect.flip(Effect.provide(open, Layer.fresh(Database.layer({ filename }))))
              assert.instanceOf(second, Database.DatabaseInUse)
            }),
          )
          // Once the first has closed, the next can open it.
          yield* Effect.provide(open, Layer.fresh(Database.layer({ filename })))
        }),
      ),
    // The second opener waits out SQLite's busy timeout, five seconds, before it gives up.
    15_000,
  )

  it.effect('lets a later migration rebuild a table that others reference', () =>
    withFile((filename) =>
      Effect.gen(function* () {
        const deviceId = `dev_${'0'.repeat(32)}`
        const referenced = Effect.gen(function* () {
          const sql = yield* SqlClient.SqlClient
          yield* sql.unsafe(`INSERT INTO devices (id, name, created_at) VALUES ('${deviceId}', 'Mac', '2026-09-28T20:34:23.123Z')`)
          yield* sql.unsafe(
            `INSERT INTO runtime_instances (id, device_id, pid, app_version, started_at) VALUES ('rt_${'0'.repeat(32)}', '${deviceId}', 42, '0.0.0', '2026-09-28T20:34:23.123Z')`,
          )
        })
        yield* Effect.provide(referenced, Layer.fresh(Database.layer({ filename })))
        const rebuildDevices = {
          key: `${String(migrations.length + 1).padStart(4, '0')}_rebuild_devices`,
          statements: [
            'CREATE TABLE devices_new (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, created_at TEXT NOT NULL) STRICT',
            'INSERT INTO devices_new SELECT id, name, created_at FROM devices',
            'DROP TABLE devices',
            'ALTER TABLE devices_new RENAME TO devices',
          ],
        }
        const after = Effect.gen(function* () {
          const sql = yield* SqlClient.SqlClient
          const applied = yield* sql<{ name: string }>`SELECT name FROM schema_migrations ORDER BY migration_id`
          const [instance] = yield* sql<{ deviceId: string }>`SELECT device_id FROM runtime_instances`
          return { applied: applied.map((row) => row.name), deviceId: instance?.deviceId }
        })
        const result = yield* Effect.provide(after, Layer.fresh(Database.layer({ filename, migrations: [...migrations, rebuildDevices] })))
        assert.deepStrictEqual(result, { applied: [...migrations.map((migration) => migration.key.slice(5)), 'rebuild_devices'], deviceId })
      }),
    ),
  )

  it.effect('gives the projects made before inks had one an ink each, in the order they were made', () =>
    withFile((filename) =>
      Effect.gen(function* () {
        const before = migrations.findIndex((migration) => migration.key === '0011_home')
        const made = Effect.gen(function* () {
          const sql = yield* SqlClient.SqlClient
          const actor = `act_${'0'.repeat(32)}`
          yield* sql.unsafe(
            `INSERT INTO actors (id, kind, display_name, created_at) VALUES ('${actor}', 'person', 'You', '2026-09-28T20:34:23.123Z')`,
          )
          // Nine projects, the last two made in the same millisecond: the ninth starts the inks again.
          for (const n of [1, 2, 3, 4, 5, 6, 7, 8, 9])
            yield* sql.unsafe(
              `INSERT INTO projects (id, name, slug, created_by_actor_id, created_at) VALUES ('proj_${String(n).padStart(32, '0')}', 'P${n}', 'p${n}', '${actor}', '2026-09-28T20:34:2${Math.min(n, 8)}.000Z')`,
            )
        })
        yield* Effect.provide(made, Layer.fresh(Database.layer({ filename, migrations: migrations.slice(0, before) })))
        const inks = Effect.flatMap(SqlClient.SqlClient, (sql) => sql<{ ink: string }>`SELECT ink FROM projects ORDER BY created_at, rowid`)
        const after = yield* Effect.provide(inks, Layer.fresh(Database.layer({ filename })))
        assert.deepStrictEqual(
          after.map((row) => row.ink),
          ['clay', 'ochre', 'olive', 'moss', 'teal', 'slate', 'rose', 'umber', 'clay'],
        )
      }),
    ),
  )

  it.effect('refuses to open a database whose rows point at nothing', () =>
    withFile((filename) =>
      Effect.gen(function* () {
        const orphan = Effect.gen(function* () {
          const sql = yield* SqlClient.SqlClient
          yield* sql`PRAGMA foreign_keys = OFF`
          yield* sql.unsafe(
            `INSERT INTO projects (id, name, slug, created_by_actor_id, created_at) VALUES ('proj_${'0'.repeat(32)}', 'X', 'x', 'act_${'0'.repeat(32)}', '2026-09-28T20:34:23.123Z')`,
          )
        })
        yield* Effect.provide(orphan, Layer.fresh(Database.layer({ filename })))
        const error = yield* Effect.flip(Effect.provide(Effect.void, Layer.fresh(Database.layer({ filename }))))
        assert.instanceOf(error, ForeignKeyViolations)
        assert.deepStrictEqual((error as ForeignKeyViolations).tables, ['projects'])
      }),
    ),
  )
})
