import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { assert, describe, it } from '@effect/vitest'
import { Effect } from 'effect'

import { coAuthorLine, creditBranch, type CreditOptions, creditedMessage, forgetful, type Memory, withoutAgentCredit } from '../src/credit'
import { remoteTip } from '../src/git'
import { repository } from './support'

/*
 * What leaves the Mac carries the person as author and Althar as co-author,
 * never an agent's own credit; and nothing already shared is rewritten.
 */

const on = { coAuthor: true, agents: ['Claude Code', 'Codex', 'OpenCode'] }
const off = { ...on, coAuthor: false }

describe('a commit message', () => {
  it('loses the agents’ credit and gains Althar’s', () => {
    const message = [
      'Retry failed upstream calls',
      '',
      'Backs off twice before giving up.',
      '',
      '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      '',
      'Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>',
      '',
    ].join('\n')
    assert.strictEqual(
      creditedMessage(message, on),
      ['Retry failed upstream calls', '', 'Backs off twice before giving up.', '', coAuthorLine, ''].join('\n'),
    )
    assert.strictEqual(creditedMessage(message, off), 'Retry failed upstream calls\n\nBacks off twice before giving up.\n')
  })

  it('joins trailers the message already ends with, and keeps the people in them', () => {
    const message = 'Fix the login\n\nSigned-off-by: Ada <ada@example.com>\nCo-authored-by: Claude Monet <claude@monet.fr>\n'
    assert.strictEqual(creditedMessage(message, on), `${message}${coAuthorLine}\n`)
    assert.strictEqual(creditedMessage(message, off), message)
  })

  it('knows the other agents by name and address, the ones Althar runs among them', () => {
    const lines = [
      'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
      'Co-authored-by: Cursor Agent <cursoragent@cursor.com>',
      'Co-authored-by: aider (gpt-5) <aider@aider.chat>',
      'Co-authored-by: OpenCode <noreply@opencode.ai>',
      'Co-authored-by: Codex <codex@openai.com>',
      'Assisted-by: Gemini CLI',
      'Generated with Codex',
      '🤖 Generated by Claude Opus 4.6',
    ]
    for (const line of lines) assert.strictEqual(creditedMessage(`Change it\n\n${line}\n`, off), 'Change it\n', line)
    assert.strictEqual(
      creditedMessage('Change it\n\nCo-authored-by: Pilot <pilot@noreply.test>\n', { coAuthor: false, agents: ['Pilot'] }),
      'Change it\n',
    )
  })

  it('leaves a person’s sentence and a person’s address alone, their GitHub one too', () => {
    const kept = [
      'Use the tokenizer\n\nGenerated with GPT-4 tokenizer data from the 2024 dump.\n',
      'Pair on it\n\nCo-authored-by: Claude Shannon <claude@bell-labs.com>\n',
      'Pair on it\n\nCo-authored-by: Devin Johnson <1234+devinj@users.noreply.github.com>\n',
      'Pair on it\n\nCo-authored-by: Claude Martin <99+cmartin@users.noreply.github.com>\n',
      'Credit\n\nThe theory was written by Claude Shannon.\n',
      'Credit\n\nCreated by Claude Monet\n',
      'Explain trailers\n\n    Co-Authored-By: Claude <noreply@anthropic.com>\n',
      'Keep the code\n\n```\nCo-Authored-By: Claude <noreply@anthropic.com>\n```\n',
      'Keep spacing\n\na\n\n\nb\n',
      'Pair on it\n\nCo-authored-by: Claude Martin <claude.martin@anthropic.com>\n',
      'Credit\n\nCreated by [Claude Monet](https://example.org/claude-monet)\n',
      'Pair on it\n\nCo-authored-by: Devin Lee <1234+devin-lee@users.noreply.github.com>\n',
      'Pair on it\n\nCo-authored-by: Jules V <5+jules-v@users.noreply.github.com>\n',
      'Thank the bot\n\nCo-authored-by: campaign-roomba[bot] <7+campaign-roomba[bot]@users.noreply.github.com>\n',
    ]
    for (const message of kept) assert.strictEqual(creditedMessage(message, off), message)
  })

  it('knows GitHub’s bots by their accounts', () => {
    for (const line of [
      'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
      'Co-authored-by: google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>',
      'Co-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>',
    ])
      assert.strictEqual(creditedMessage(`Change it\n\n${line}\n`, off), 'Change it\n', line)
  })

  it('reads a fence never closed as text, and comes out the same twice', () => {
    const message = `Odd fence\n\n\`\`\`\nsome code${claude}\n`
    const once = creditedMessage(message, on)
    assert.strictEqual(once, `Odd fence\n\n\`\`\`\nsome code\n\n${coAuthorLine}\n`)
    assert.strictEqual(creditedMessage(once, on), once)
  })

  it('joins trailers written with CRLF', () => {
    assert.strictEqual(
      creditedMessage('Fix it\r\n\r\nSigned-off-by: Ada <ada@example.com>\r\n', on),
      `Fix it\r\n\r\nSigned-off-by: Ada <ada@example.com>\r\n${coAuthorLine}\n`,
    )
  })

  it('leaves a message that is all credit as it was, rather than empty', () => {
    const message = 'Co-Authored-By: Claude <noreply@anthropic.com>\n'
    assert.strictEqual(creditedMessage(message, on), message)
  })

  it('needs nothing twice: a message already credited comes back the same', () => {
    const once = creditedMessage('Change it\n', on)
    assert.strictEqual(once, `Change it\n\n${coAuthorLine}\n`)
    assert.strictEqual(creditedMessage(once, on), once)
    assert.strictEqual(creditedMessage(once, off), 'Change it\n')
  })

  it('takes the agents’ footer out of a pull request’s description', () => {
    assert.strictEqual(
      withoutAgentCredit('Adds a retry.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)', on.agents),
      'Adds a retry.',
    )
  })
})

const git = (cwd: string, ...args: Array<string>) =>
  execFileSync('git', ['-c', 'user.name=Ada', '-c', 'user.email=ada@example.com', ...args], { cwd })
    .toString()
    .trim()

const commit = (cwd: string, file: string, message: string) => {
  writeFileSync(join(cwd, file), file)
  git(cwd, 'add', '.')
  git(cwd, 'commit', '-q', '-m', message)
  return git(cwd, 'rev-parse', 'HEAD')
}

const claude = '\n\nCo-Authored-By: Claude <noreply@anthropic.com>'

/** A repository the person works in as Ada, as agents commit for them. */
const ours = () => {
  const path = repository()
  git(path, 'config', 'user.name', 'Ada')
  git(path, 'config', 'user.email', 'ada@example.com')
  return path
}

/** A task's branch off main, credited from `head` (its tip unless said), as Althar would before a send. */
const credit = (path: string, options: Partial<CreditOptions> & { readonly coAuthor: boolean; readonly agents: ReadonlyArray<string> }) =>
  creditBranch(path, 'task', { known: [], memory: forgetful, head: git(path, 'rev-parse', 'task'), ...options })

/** A memory that keeps what it is told, as the profile does: each original, and each credited commit as done. */
const remembering = (): Memory & { readonly kept: Map<string, string> } => {
  const kept = new Map<string, string>()
  return {
    kept,
    recall: (commits) =>
      Effect.succeed(
        new Map(
          commits.flatMap((one) => {
            const original = kept.get(one)
            if (original !== undefined) return [[one, original] as const]
            return [...kept.values()].includes(one) ? [[one, one] as const] : []
          }),
        ),
      ),
    remember: (made) => Effect.sync(() => made.forEach((one) => kept.set(one.original, one.credited))),
  }
}

const messages = (path: string, range: string) =>
  git(path, 'log', '--format=%B%x00', range)
    .split('\0')
    .map((message) => message.trim())
    .filter(Boolean)

describe('a branch', () => {
  it.effect('is made again where it is only here, author and dates kept, and moves to it once settled', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      commit(path, 'a.txt', `Add a${claude}`)
      const second = commit(path, 'b.txt', 'Add b')
      const before = git(path, 'log', '-1', '--format=%an %ae %ad %cd', second)
      const made = yield* credit(path, on)
      // Nothing moves until what it made is sent.
      assert.strictEqual(git(path, 'rev-parse', 'task'), second)
      assert.lengthOf(made.made, 2)
      yield* made.settle
      assert.strictEqual(git(path, 'rev-parse', 'task'), made.head)
      assert.deepStrictEqual(messages(path, 'main..task'), [`Add b\n\n${coAuthorLine}`, `Add a\n\n${coAuthorLine}`])
      assert.strictEqual(git(path, 'log', '-1', '--format=%an %ae %ad %cd', made.head), before)
      // the worktree holds what it held: nothing to commit
      assert.strictEqual(git(path, 'status', '--porcelain'), '')
      assert.strictEqual(git(path, 'rev-parse', 'main'), git(path, 'rev-parse', 'task~2'))
    }),
  )

  it.effect('leaves what was sent, what Althar remembers sending, and what another branch has, as it was', () =>
    Effect.gen(function* () {
      const path = ours()
      const shared = commit(path, 'shared.txt', `Shared on main${claude}`)
      git(path, 'switch', '-q', '-c', 'task')
      const sent = commit(path, 'a.txt', `Sent already${claude}`)
      const remembered = commit(path, 'b.txt', `Sent by Althar${claude}`)
      commit(path, 'c.txt', `Not yet${claude}`)
      const made = yield* credit(path, {
        ...off,
        known: [sent, 'f'.repeat(40)],
        memory: {
          ...forgetful,
          recall: (commits) => Effect.succeed(new Map(commits.filter((one) => one === remembered).map((one) => [one, one]))),
        },
      })
      yield* made.settle
      assert.strictEqual(git(path, 'rev-parse', 'task~3'), shared)
      assert.strictEqual(git(path, 'rev-parse', 'task~2'), sent)
      assert.strictEqual(git(path, 'rev-parse', 'task~1'), remembered)
      assert.strictEqual(git(path, 'log', '-1', '--format=%B', 'task'), 'Not yet')
    }),
  )

  it.effect('sends a head that went before as it is, though the branch has more after it', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      const sent = commit(path, 'a.txt', `Sent${claude}`)
      const later = commit(path, 'b.txt', `Later${claude}`)
      const made = yield* credit(path, { ...on, head: sent, known: [sent] })
      assert.strictEqual(made.head, sent)
      // What comes after is made again all the same, and remembered, for when it goes.
      assert.deepStrictEqual(
        made.made.map((one) => one.original),
        [later],
      )
    }),
  )

  it.effect('goes the way it went before, whatever the setting says now', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      const head = commit(path, 'a.txt', `Add a${claude}`)
      const memory = remembering()
      const first = yield* credit(path, { ...on, memory })
      // Made with Althar's line; the person turns it off; the branch never moved (an agent was committing).
      const again = yield* credit(path, { ...off, memory })
      assert.strictEqual(again.head, first.head)
      assert.notStrictEqual(again.head, head)
      assert.deepStrictEqual([...memory.kept], [[head, first.head]])
    }),
  )

  it.effect('keeps what a merge brought in from elsewhere, and makes only the branch’s own line again', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      commit(path, 'a.txt', `Add a${claude}`)
      // A colleague's commit, fetched from somewhere no ref here names, and merged.
      const colleague = repository()
      const theirs = commit(colleague, 'theirs.txt', `Theirs${claude}`)
      git(path, 'fetch', '-q', colleague, 'main')
      git(path, 'merge', '-q', '--no-edit', '--allow-unrelated-histories', 'FETCH_HEAD')
      const made = yield* credit(path, on)
      yield* made.settle
      const parents = git(path, 'rev-list', '--parents', '-n', '1', 'task').split(' ')
      assert.strictEqual(parents[2], theirs)
      assert.include(git(path, 'log', '-1', '--format=%B', 'task^1'), coAuthorLine)
      assert.notInclude(git(path, 'log', '-1', '--format=%B', theirs), coAuthorLine)
    }),
  )

  it.effect('leaves a colleague’s commits the branch was rebased onto as they were', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      // Bob's pull request, fetched from where no ref here names it, built on.
      const bob = execFileSync(
        'git',
        ['-c', 'user.name=Bob', '-c', 'user.email=bob@example.com', 'commit', '-q', '--allow-empty', '-m', `Bob's work${claude}`],
        { cwd: path },
      )
      void bob
      const bobs = git(path, 'rev-parse', 'HEAD')
      commit(path, 'a.txt', `Ada's agent${claude}`)
      const made = yield* credit(path, on)
      yield* made.settle
      assert.strictEqual(git(path, 'rev-parse', 'task~1'), bobs)
      assert.include(git(path, 'log', '-1', '--format=%B', 'task'), coAuthorLine)
    }),
  )

  it.effect('goes as it is where a colleague’s commit would have to move, or a commit in another encoding would be spoilt', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      commit(path, 'a.txt', `Ada's agent${claude}`)
      execFileSync(
        'git',
        ['-c', 'user.name=Bob', '-c', 'user.email=bob@example.com', 'commit', '-q', '--allow-empty', '-m', 'Bob on top'],
        {
          cwd: path,
        },
      )
      const tip = git(path, 'rev-parse', 'task')
      const moved = yield* credit(path, on)
      assert.strictEqual(moved.head, tip)
      assert.deepStrictEqual(moved.made, [])

      const latin = ours()
      git(latin, 'switch', '-q', '-c', 'task')
      git(latin, '-c', 'i18n.commitEncoding=ISO-8859-1', 'commit', '-q', '--allow-empty', '-m', `Caf\u00e9${claude}`)
      const head = git(latin, 'rev-parse', 'task')
      assert.strictEqual((yield* credit(latin, on)).head, head)
    }),
  )

  it.effect('doesn’t move the branch from under a merge the lead has under way', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      writeFileSync(join(path, 'README.md'), 'ours\n')
      git(path, 'commit', '-q', '-am', `Ours${claude}`)
      git(path, 'switch', '-q', 'main')
      writeFileSync(join(path, 'README.md'), 'theirs\n')
      git(path, 'commit', '-q', '-am', 'Theirs')
      git(path, 'switch', '-q', 'task')
      const tip = git(path, 'rev-parse', 'task')
      assert.throws(() => git(path, 'merge', '-q', 'main'))
      const made = yield* credit(path, on)
      yield* made.settle
      assert.strictEqual(git(path, 'rev-parse', 'task'), tip)
      git(path, 'merge', '--abort')
    }),
  )

  it.effect('doesn’t move the branch from under a rebase the lead has under way', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      writeFileSync(join(path, 'README.md'), 'ours\n')
      git(path, 'commit', '-q', '-am', `Ours${claude}`)
      git(path, 'switch', '-q', 'main')
      writeFileSync(join(path, 'README.md'), 'theirs\n')
      git(path, 'commit', '-q', '-am', 'Theirs')
      git(path, 'switch', '-q', 'task')
      const tip = git(path, 'rev-parse', 'task')
      assert.throws(() => git(path, 'rebase', '-q', 'main'))
      const made = yield* credit(path, { ...on, head: tip })
      yield* made.settle
      assert.strictEqual(git(path, 'rev-parse', 'task'), tip)
      git(path, 'rebase', '--abort')
    }),
  )

  it.effect('makes the same commits each time, and credits what an agent committed meanwhile onto what was sent', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      commit(path, 'a.txt', `Add a${claude}`)
      const once = yield* credit(path, on)
      const twice = yield* credit(path, on)
      assert.strictEqual(once.head, twice.head)
      const later = commit(path, 'b.txt', 'Add b')
      yield* once.settle
      // The agent's commit now sits on what was sent, credited too.
      assert.strictEqual(git(path, 'rev-parse', 'task~1'), once.head)
      assert.notStrictEqual(git(path, 'rev-parse', 'task'), later)
      assert.deepStrictEqual(messages(path, 'main..task'), [`Add b\n\n${coAuthorLine}`, `Add a\n\n${coAuthorLine}`])
    }),
  )

  it.effect('signs what it makes again where the person has git sign their commits', () =>
    Effect.gen(function* () {
      const path = ours()
      const key = join(path, '.git', 'signing-key')
      execFileSync('ssh-keygen', ['-q', '-t', 'ed25519', '-N', '', '-f', key])
      git(path, 'config', 'gpg.format', 'ssh')
      git(path, 'config', 'user.signingkey', key)
      git(path, 'config', 'commit.gpgsign', 'true')
      git(path, 'switch', '-q', '-c', 'task')
      commit(path, 'a.txt', `Add a${claude}`)
      const made = yield* credit(path, on)
      assert.include(git(path, 'cat-file', 'commit', made.head), 'gpgsig')
    }),
  )

  it.effect('signs again a commit that was signed, though git doesn’t sign every commit here', () =>
    Effect.gen(function* () {
      const path = ours()
      const key = join(path, '.git', 'signing-key')
      execFileSync('ssh-keygen', ['-q', '-t', 'ed25519', '-N', '', '-f', key])
      git(path, 'config', 'gpg.format', 'ssh')
      git(path, 'config', 'user.signingkey', key)
      git(path, 'switch', '-q', '-c', 'task')
      writeFileSync(join(path, 'a.txt'), 'a')
      git(path, 'add', '.')
      git(path, 'commit', '-q', '-S', '-m', `Signed by hand${claude}`)
      const made = yield* credit(path, on)
      assert.include(git(path, 'cat-file', 'commit', made.head), 'gpgsig')
    }),
  )

  it.effect('makes a signed commit the person saw the same way every time, by what it remembers', () =>
    Effect.gen(function* () {
      const path = ours()
      const key = join(path, '.git', 'signing-key')
      execFileSync('ssh-keygen', ['-q', '-t', 'ed25519', '-N', '', '-f', key])
      git(path, 'config', 'gpg.format', 'ssh')
      git(path, 'config', 'user.signingkey', key)
      git(path, 'config', 'commit.gpgsign', 'true')
      git(path, 'switch', '-q', '-c', 'task')
      const first = commit(path, 'a.txt', `Add a${claude}`)
      const second = commit(path, 'b.txt', `Add b${claude}`)
      const memory = remembering()
      // The first is pushed; the branch moves onto both, credited.
      const pushed = yield* credit(path, { ...on, memory, head: first })
      yield* pushed.settle
      // Later the second, as the person saw it before: it is the one now on the branch.
      const later = yield* credit(path, { ...on, memory, head: second, known: [pushed.head] })
      assert.strictEqual(later.head, git(path, 'rev-parse', 'task'))
    }),
  )

  it.effect('leaves what the remote has, asked by its address, as it was: a branch pushed before Althar credited anything', () =>
    Effect.gen(function* () {
      const path = ours()
      const bare = mkdtempSync(join(tmpdir(), 'althar-bare-'))
      git(bare, 'init', '-q', '--bare')
      git(path, 'switch', '-q', '-c', 'task')
      const pushed = commit(path, 'a.txt', `Pushed before${claude}`)
      git(path, 'push', '-q', bare, 'task')
      commit(path, 'b.txt', `Not yet${claude}`)
      const tip = yield* remoteTip(path, { url: bare, header: null }, 'task')
      assert.strictEqual(tip, pushed)
      assert.isNull(yield* remoteTip(path, { url: bare, header: null }, 'other'))
      // With the connection's header, as a push to a code host signs in.
      assert.strictEqual(yield* remoteTip(path, { url: bare, header: 'Authorization: Basic eDp5' }, 'task'), pushed)
      const made = yield* credit(path, { ...on, known: [tip] })
      yield* made.settle
      assert.strictEqual(git(path, 'rev-parse', 'task~1'), pushed)
      git(path, 'push', '-q', bare, 'task')
    }),
  )

  it.effect('leaves a branch that isn’t there, or needs nothing, as it is', () =>
    Effect.gen(function* () {
      const path = ours()
      git(path, 'switch', '-q', '-c', 'task')
      const head = commit(path, 'a.txt', 'Plain')
      const plain = yield* credit(path, off)
      yield* plain.settle
      assert.strictEqual(plain.head, head)
      assert.strictEqual(git(path, 'rev-parse', 'task'), head)
      const gone = yield* creditBranch(path, 'renamed', { ...on, known: [], memory: forgetful, head })
      assert.strictEqual(gone.head, head)
    }),
  )
})
